[project]
name = "hotelmanagement"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Sanket Mane", email = "trendingzone15@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "django>=6.1.2",
    "djangorestframework>=3.18.3",
    "djangorestframework-simplejwt>=5.5.1",
]

[project.scripts]
hotelmanagement = "hotelmanagement:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"
